### http200 - Успех
# Запрос без указания кода страны.
# Возвращает данные о погоде для города Курганинск.
# Подходит для уникальных названий городов.
GET https://api.openweathermap.org/data/2.5/weather?q=Kurganinsk&appid=66b4f9f34b5073497f497f4d4f2be438

### http200 - Успех
# Запрос с указанием кода страны.
# Возвращает данные о погоде для города Курганинск в России.
# Рекомендуется для точного определения местоположения, особенно если город не уникален.
GET https://api.openweathermap.org/data/2.5/weather?q=Kurganinsk,RU&appid=66b4f9f34b5073497f497f4d4f2be438

### http200 - Успех
# Запрос с указанием кода региона и страны.
# Возвращает данные о погоде для города Курганинск в Краснодарском крае, Россия.
# Обеспечивает более точные данные, когда в стране есть несколько регионов с одинаковыми или похожими названиями городов.
GET https://api.openweathermap.org/data/2.5/weather?q=Kurganinsk,KDA,RU&appid=66b4f9f34b5073497f497f4d4f2be438
