### http200 - Успех
# Запрос с использованием географических координат.
# Возвращает данные о погоде для Курганинска по широте и долготе.
# Этот метод полезен, когда точные координаты местоположения известны.
GET https://api.openweathermap.org/data/2.5/weather?lat=44.867&lon=40.617&appid=66b4f9f34b5073497f497f4d4f2be438
