CREATE TABLE Locations
(
    id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(100),
    user_id   INTEGER,
    latitude  DECIMAL(40, 35),
    longitude DECIMAL(40, 35),
    FOREIGN KEY (user_id) REFERENCES Users (id)
)
