CREATE TABLE Locations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    user_id INTEGER,
    latitude DECIMAL(20, 18),
    longitude DECIMAL(20, 18),
    FOREIGN KEY (user_id) REFERENCES Users(id)
);
